# Generated by Django 4.0.3 on 2022-04-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0002_remove_post_imagen_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
