# Generated by Django 4.0.3 on 2022-04-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0003_post_imagen_delete_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introduccion',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
