# Generated by Django 4.0.3 on 2022-04-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0005_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
