# Generated by Django 4.0.3 on 2022-04-24 15:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0006_delete_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
