# Generated by Django 4.0.3 on 2022-04-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0008_post1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
