# Generated by Django 4.0.3 on 2022-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appmensaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='autor',
            field=models.CharField(max_length=40),
        ),
    ]
